/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.thjava.views;

import java.sql.*;
import javax.swing.JOptionPane;

/**
 *
 * @author Admin
 */
public class AddBook extends javax.swing.JFrame {

    // 1. ประกาศตัวแปร และกำหนดค่าเริ่มต้น
    private String driver = "com.mysql.jdbc.Driver";
    private String utf_8 = "?useUnicode=true&characterEncoding=UTF-8";
    private String url = "jdbc:mysql://localhost:3306/JAVA_OOP_V1" + utf_8;
    private String username = "root";
    private String password = "";

    private Connection connect;

    public AddBook() {
        initComponents();
    }
    
    // เตรียมสร้างเมธอด
    public void addBook() {
        try {
            
            // 2. เตรียมข้อมูลที่จะบันทึก
            String title = txtTitle.getText().trim();
            String price = txtPrice.getText().trim();
            //System.out.println("ชื่อ: " + title + " ราคา: " + price);
            
            // 3. เชื่อมต่อฐานข้อมูล
            Class.forName(driver);
            connect = DriverManager.getConnection(url, username, password);
            //System.out.println("เชื่อมต่อสำเร็จ");
            
            // 4. เตรียมคำสั่ง SQL
            String sql = "INSERT INTO BOOKS VALUES (?, ?, ?)";
            PreparedStatement ps = connect.prepareStatement(sql);
            ps.setInt(1, 0);
            ps.setString(2, title);
            ps.setInt(3, Integer.parseInt(price));
            
            // 5. ประมวลผลคำสั่ง SQL
            int result = ps.executeUpdate();
            
            // 6. แจ้งผลลัพธ์
            if(result > 0) {
                //System.out.println("บันทึกสำเร็จ");
                JOptionPane.showMessageDialog(this, "บันทึกสำเร็จ", "แจ้งผลลัพธ์", 1);
                txtTitle.setText("");
                txtPrice.setText("");
            }
            
            // 7. ปิดการเชื่อมต่อฐานข้อมูล
            connect.close();
            
        } catch (Exception e) {
            //System.out.println("บันทึกไม่สำเร็จ");
            JOptionPane.showMessageDialog(this, "บันทึกไม่สำเร็จ", "แจ้งผลลัพธ์", 0);
            System.exit(0);
            e.printStackTrace();
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtPrice = new javax.swing.JTextField();
        txtTitle = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnSave = new javax.swing.JButton();
        lblBg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("เพิ่มหนังสือ");

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtPrice.setFont(new java.awt.Font("TH K2D July8", 0, 18)); // NOI18N
        txtPrice.setForeground(new java.awt.Color(0, 101, 68));
        txtPrice.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtPrice.setBorder(null);
        jPanel1.add(txtPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, 320, 40));

        txtTitle.setFont(new java.awt.Font("TH K2D July8", 0, 18)); // NOI18N
        txtTitle.setForeground(new java.awt.Color(0, 101, 68));
        txtTitle.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtTitle.setBorder(null);
        jPanel1.add(txtTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, 320, 40));

        jLabel1.setFont(new java.awt.Font("TH K2D July8", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 2, 98));
        jLabel1.setText("ราคา");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, 320, 30));

        jLabel2.setFont(new java.awt.Font("TH K2D July8", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 2, 98));
        jLabel2.setText("ชื่อหนังสือ");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 320, 30));

        btnSave.setBackground(new java.awt.Color(177, 231, 223));
        btnSave.setFont(new java.awt.Font("TH K2D July8", 0, 24)); // NOI18N
        btnSave.setForeground(new java.awt.Color(0, 101, 68));
        btnSave.setText("บันทึก");
        btnSave.setFocusPainted(false);
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        jPanel1.add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 250, 120, 40));

        lblBg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/thjava/imgs/bg.png"))); // NOI18N
        jPanel1.add(lblBg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        addBook();
    }//GEN-LAST:event_btnSaveActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSave;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblBg;
    private javax.swing.JTextField txtPrice;
    private javax.swing.JTextField txtTitle;
    // End of variables declaration//GEN-END:variables
}
