/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.thjava.views;

import java.sql.*;

/**
 *
 * @author Admin
 */
public class ShowBooks extends javax.swing.JFrame {

    /**
     * Creates new form ListBooks
     */
	
    // 1. ประกาศตัวแปร และกำหนดค่าเริ่มต้น
    private String driver = "com.mysql.jdbc.Driver";
    private String utf_8 = "?useUnicode=true&characterEncoding=UTF-8";
    private String url = "jdbc:mysql://localhost:3306/JAVA_OOP_V1" + utf_8;
    private String username = "root";
    private String password = "";
    
    private Connection connect;
	
    public ShowBooks() {
        initComponents();
        showBooks();
    }
    
    // เตรียมสร้างเมธอด
    public void showBooks() {
        try {
            // 2. เชื่อมต่อฐานข้อมูล
            Class.forName(driver);
            connect = DriverManager.getConnection(url, username, password);
            //System.out.println("เชื่อมต่อสำเร็จ");
            
            // 3. เตรียมคำสั่ง SQL
            String sql = "SELECT * FROM BOOKS;";
            PreparedStatement ps = connect.prepareStatement(sql);
            
            // 4. ประมวลผลคำสั่ง SQL
            ResultSet result = ps.executeQuery();
            
            // 5. แสดงผลลัพธ์
            while(result.next()) {
                
                String text = "รหัส: " + result.getInt("id")
                            + " ชื่อ: " + result.getString("title")
                            + " ราคา: " +result.getInt("price")
                            + " \n";
                
                txtAreaBooks.append(text);
            }
            
            // 6. ปิดการเชื่อมต่อฐานข้อมูล
            connect.close();
            
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAreaBooks = new javax.swing.JTextArea();
        lblBg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("รายการหนังสือ");

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtAreaBooks.setEditable(false);
        txtAreaBooks.setColumns(20);
        txtAreaBooks.setRows(5);
        txtAreaBooks.setFocusable(false);
        jScrollPane1.setViewportView(txtAreaBooks);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 340, 200));

        lblBg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/thjava/imgs/bg.png"))); // NOI18N
        jPanel1.add(lblBg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 300));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblBg;
    private javax.swing.JTextArea txtAreaBooks;
    // End of variables declaration//GEN-END:variables
}
