/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.thjava.views;

import com.thjava.m.Books;
import java.util.List;

/**
 *
 * @author Admin
 */
public class ShowBooks extends javax.swing.JFrame {

    /**
     * Creates new form ListBooks
     */

    public ShowBooks() {
        initComponents();
    }
    
    // แสดงรายการหนังสือ
    public void showBooks(List<Books> bList) {
        for (Books b : bList) {
            String text = "รหัส: " + b.getId() 
                        + " ชื่อ: " + b.getTitle()
                        + " ราคา: " + b.getPrice()
                        + " \n";
            txtAreaBooks.append(text);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAreaBooks = new javax.swing.JTextArea();
        lblBg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("รายการหนังสือ");

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtAreaBooks.setEditable(false);
        txtAreaBooks.setColumns(20);
        txtAreaBooks.setRows(5);
        txtAreaBooks.setFocusable(false);
        jScrollPane1.setViewportView(txtAreaBooks);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 340, 200));

        lblBg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/thjava/imgs/bg.png"))); // NOI18N
        jPanel1.add(lblBg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 300));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblBg;
    private javax.swing.JTextArea txtAreaBooks;
    // End of variables declaration//GEN-END:variables
}
